In [703]:
#Importing our defined functions
from clean_data_functions import *

In [704]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
import re 

url = 'Airbnb_berlin.xlsx'
airbnb_df = pd.read_excel(url)

# Cleaning Berlin Airbnb for Price

In [705]:
airbnb_df.head()

,ID,Neighbourhood,Neighbourhood Cleansed,City,State,Country Code,Country,Latitude,Longitude,Property Type,...,Calendar last Scraped,Number of Reviews,Review Scores Rating,Review Scores Accuracy,Review Scores Cleanliness,Review Scores Checkin,Review Scores Communication,Review Scores Location,Review Scores Value,Cancellation Policy
0,11241690,Schmargendorf,Grunewald,Berlin,Berlin,DE,Germany,52492584679892568,13291125230320348,Apartment,...,2017-05-08,36,91.0,9.0,9.0,9.0,9.0,9.0,9.0,strict
1,18185889,NaN,Friedrichsfelde Nord,Berlin,Berlin,DE,Germany,5251333712080716,1352300560443927,Apartment,...,2017-05-08,1,100.0,10.0,10.0,10.0,10.0,10.0,10.0,moderate
2,15016170,NaN,Neu Lichtenberg,Berlin,Berlin,DE,Germany,52505657480362616,13477532800621064,Apartment,...,2017-05-08,6,92.0,10.0,10.0,10.0,10.0,10.0,9.0,strict
3,14793734,NaN,Neu Lichtenberg,Berlin,Berlin,DE,Germany,5250811173606898,13502193139685872,Apartment,...,2017-05-08,9,93.0,10.0,10.0,10.0,10.0,9.0,10.0,flexible
4,11528511,NaN,Neu Lichtenberg,Berlin,Berlin,DE,Germany,5250421911808095,13488966994018384,Apartment,...,2017-05-08,3,93.0,9.0,9.0,9.0,9.0,9.0,10.0,moderate

In [706]:
# Get unique values from 'Neighbourhood'
unique_neighbourhoods = airbnb_df['Neighbourhood'].unique()

# Clean the Neighbourhood Column
airbnb_df['Neighbourhood Cleansed'] = airbnb_df['Neighbourhood Cleansed'].str.split('[ \-\/]')
# df['SplitColumn'] = df['SplitColumn'].apply(np.array)
airbnb_df['Neighbourhood Cleansed'] = airbnb_df['Neighbourhood Cleansed'].apply(
    lambda x: [item for item in x if item in unique_neighbourhoods])

airbnb_df['Neighbourhood Cleansed'] = airbnb_df['Neighbourhood Cleansed'].apply(lambda x: ' '.join(x))

# Fill NaN values in 'Neighbourhood' with values from 'Neighbourhood Cleansed'
airbnb_df['Neighbourhood'] = airbnb_df['Neighbourhood'].fillna(airbnb_df['Neighbourhood Cleansed'])

In [707]:
# Drop not needed Columns
airbnb_df = airbnb_df.drop(['ID', 'Neighbourhood Cleansed', 'City', 'State', 'Country', 'Country Code', 'Latitude', 'Longitude', 'Amenities', 'Calendar last Scraped', 'Review Scores Accuracy', 'Review Scores Cleanliness', 'Review Scores Checkin', 'Review Scores Communication', 'Review Scores Location', 'Review Scores Value', 'Weekly Price', 'Monthly Price', 'Square Feet', 'Review Scores Rating'], axis=1)

In [708]:
airbnb_df

,Neighbourhood,Property Type,Room Type,Accommodates,Bathrooms,Bedrooms,Beds,Bed Type,Price,Security Deposit,Cleaning Fee,Guests Included,Extra People,Minimum Nights,Maximum Nights,Availability 365,Number of Reviews,Cancellation Policy
0,Schmargendorf,Apartment,Entire home/apt,6,10.0,3.0,6.0,Real Bed,95.0,NaN,75.0,2,20,2,1125,170,36,strict
1,Friedrichsfelde,Apartment,Private room,2,10.0,1.0,1.0,Real Bed,49.0,NaN,NaN,1,0,1,1125,64,1,moderate
2,Lichtenberg,Apartment,Entire home/apt,2,10.0,1.0,1.0,Pull-out Sofa,32.0,180.0,35.0,1,25,3,20,45,6,strict
3,Lichtenberg,Apartment,Entire home/apt,2,10.0,1.0,1.0,Real Bed,40.0,NaN,10.0,1,0,1,5,212,9,flexible
4,Lichtenberg,Apartment,Private room,2,10.0,1.0,1.0,Pull-out Sofa,35.0,NaN,10.0,1,0,2,11,9,3,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20571,SchÃ¶neberg,Apartment,Private room,2,10.0,1.0,1.0,Real Bed,25.0,100.0,NaN,1,10,2,3,0,2,moderate
20572,Reinickendorf,Apartment,Private room,2,10.0,1.0,1.0,Pull-out Sofa,38.0,NaN,NaN,1,5,1,6,0,7,flexible
20573,Reinickendorf,Apartment,Private room,2,10.0,1.0,1.0,Pull-out Sofa,45.0,NaN,25.0,1,30,2,32,365,3,moderate
20574,Reinickendorf,Apartment,Entire home/apt,2,10.0,1.0,1.0,Real Bed,35.0,NaN,6.0,1,0,2,1125,11,3,moderate
20575,Reinickendorf,Apartment,Shared room,1,10.0,1.0,1.0,Real Bed,50.0,NaN,10.0,1,0,1,14,89,0,flexible

In [709]:
airbnb_df = airbnb_df.dropna(subset=['Price'])

In [710]:
airbnb_df = airbnb_df.dropna()

In [711]:
null_check(airbnb_df)

Total null values per row:
2        0
5        0
8        0
12       0
15       0
        ..
20556    0
20559    0
20563    0
20565    0
20566    0
Length: 5819, dtype: int64

Total null values per column:
Neighbourhood          0
Property Type          0
Room Type              0
Accommodates           0
Bathrooms              0
Bedrooms               0
Beds                   0
Bed Type               0
Price                  0
Security Deposit       0
Cleaning Fee           0
Guests Included        0
Extra People           0
Minimum Nights         0
Maximum Nights         0
Availability 365       0
Number of Reviews      0
Cancellation Policy    0
dtype: int64

In [712]:
airbnb_df['Neighbourhood'].nunique()

87

In [713]:
# Change Neighbourhood to the major ones
filter_list= ['Reinickendorf', 'Mitte', 'Friedrichshain', 'Kreuzberg', 'Pankow', 'Charlottenburg', 'Wilmersdorf', 'Spandau', 'Steglitz', 'Zehlendorf', 'Tempelhof', 'SchÃ¶neberg', 'NeukÃ¶lln', 'Treptow', 'KÃ¶penick', 'Marzahn', 'Hellersdorf', 'Lichtenberg', 'Reinickendorf', 'Prenzlauer Berg', 'Moabit', 'Wedding', 'Tiergarten', 'HohenschÃ¶nhausen', 'WeiÃŸensee']
# Update Neighbourhood values based on filter_list
def update_neighbourhood(neighbourhood):
    for filt in filter_list:
        if filt in neighbourhood:
            return filt
    return neighbourhood

airbnb_df['Neighbourhood'] = airbnb_df['Neighbourhood'].apply(update_neighbourhood)

airbnb_df = airbnb_df[airbnb_df['Neighbourhood'].isin(filter_list)]

In [714]:
airbnb_df['Neighbourhood'].nunique()

24

In [715]:
dup_check(airbnb_df)

Duplicates found: False

Number of duplicates: 0

In [716]:
# Count each unique value in 'ColumnA'
value_counts = airbnb_df['Neighbourhood'].value_counts()

In [717]:
# Find values that appear 50 times or more
values_to_keep = value_counts[value_counts >= 50].index

# Filter the DataFrame to keep rows with those values
airbnb_df = airbnb_df[airbnb_df['Neighbourhood'].isin(values_to_keep)]

# Create DataFrame

In [718]:
# Separate the columns
categoricals_df = airbnb_df.select_dtypes(include='object')
numericals_df = airbnb_df.select_dtypes(include='number')

## Categorical

In [719]:
categoricals_df

,Neighbourhood,Property Type,Room Type,Bed Type,Cancellation Policy
12,Charlottenburg,Apartment,Entire home/apt,Real Bed,strict
15,Charlottenburg,Apartment,Entire home/apt,Real Bed,flexible
36,Charlottenburg,Apartment,Private room,Real Bed,moderate
38,Charlottenburg,Apartment,Entire home/apt,Real Bed,strict
46,Friedrichshain,Apartment,Entire home/apt,Pull-out Sofa,flexible
...,...,...,...,...,...
20556,SchÃ¶neberg,Apartment,Private room,Real Bed,strict
20559,SchÃ¶neberg,Apartment,Entire home/apt,Real Bed,moderate
20563,SchÃ¶neberg,Apartment,Entire home/apt,Real Bed,flexible
20565,SchÃ¶neberg,Loft,Entire home/apt,Real Bed,strict
20566,SchÃ¶neberg,Apartment,Entire home/apt,Real Bed,strict

### Nominals

In [720]:
# Create new Dataframes splitt in nominal and ordinal
nominal_columns = ['Neighbourhood', 'Room Type']
nominal_df = categoricals_df[nominal_columns]
nominal_df

        Neighbourhood        Room Type
12     Charlottenburg  Entire home/apt
15     Charlottenburg  Entire home/apt
36     Charlottenburg     Private room
38     Charlottenburg  Entire home/apt
46     Friedrichshain  Entire home/apt
...               ...              ...
20556      SchÃ¶neberg     Private room
20559      SchÃ¶neberg  Entire home/apt
20563      SchÃ¶neberg  Entire home/apt
20565      SchÃ¶neberg  Entire home/apt
20566      SchÃ¶neberg  Entire home/apt

[3993 rows x 2 columns]

In [721]:
# get_dummies with all the norminal columns
norminals_df = pd.get_dummies(nominal_df, dtype=int)
norminals_df

,Neighbourhood_Charlottenburg,Neighbourhood_Friedrichshain,Neighbourhood_Kreuzberg,Neighbourhood_Mitte,Neighbourhood_Moabit,Neighbourhood_NeukÃ¶lln,Neighbourhood_Pankow,Neighbourhood_Prenzlauer Berg,Neighbourhood_SchÃ¶neberg,Neighbourhood_Tempelhof,Neighbourhood_Wedding,Neighbourhood_Wilmersdorf,Room Type_Entire home/apt,Room Type_Private room,Room Type_Shared room
12,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
15,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
36,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
38,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
46,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20556,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
20559,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20563,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20565,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20566,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0

In [722]:
ordinal_df = categoricals_df[['Cancellation Policy']]

In [723]:
ordinal_df['Cancellation Policy'].unique()

array(['strict', 'flexible', 'moderate', 'super_strict_60'], dtype=object)

In [724]:
# For 'Cancellation Policy' column
enc = OrdinalEncoder(categories=[['flexible', 'moderate', 'strict', 'super_strict_60']])
ordinal_df['Cancellation Policy'] = enc.fit_transform(ordinal_df[['Cancellation Policy']])

C:\Users\vonke\AppData\Local\Temp\ipykernel_14232\1796499930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ordinal_df['Cancellation Policy'] = enc.fit_transform(ordinal_df[['Cancellation Policy']])

In [725]:
# Concat the two categorical Dataframes
result_categorical_df = pd.concat([ordinal_df, norminals_df], axis=1)
result_categorical_df

,Cancellation Policy,Neighbourhood_Charlottenburg,Neighbourhood_Friedrichshain,Neighbourhood_Kreuzberg,Neighbourhood_Mitte,Neighbourhood_Moabit,Neighbourhood_NeukÃ¶lln,Neighbourhood_Pankow,Neighbourhood_Prenzlauer Berg,Neighbourhood_SchÃ¶neberg,Neighbourhood_Tempelhof,Neighbourhood_Wedding,Neighbourhood_Wilmersdorf,Room Type_Entire home/apt,Room Type_Private room,Room Type_Shared room
12,2.0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
15,0.0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
36,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
38,2.0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
46,0.0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20556,2.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
20559,1.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20563,0.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20565,2.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
20566,2.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0

### Numberical

#### Concat both

In [726]:
final_df = pd.concat([result_categorical_df, numericals_df], axis=1)
final_df

,Cancellation Policy,Neighbourhood_Charlottenburg,Neighbourhood_Friedrichshain,Neighbourhood_Kreuzberg,Neighbourhood_Mitte,Neighbourhood_Moabit,Neighbourhood_NeukÃ¶lln,Neighbourhood_Pankow,Neighbourhood_Prenzlauer Berg,Neighbourhood_SchÃ¶neberg,...,Beds,Price,Security Deposit,Cleaning Fee,Guests Included,Extra People,Minimum Nights,Maximum Nights,Availability 365,Number of Reviews
12,2.0,1,0,0,0,0,0,0,0,0,...,1.0,27.0,100.0,20.0,1,15,21,1125,0,3
15,0.0,1,0,0,0,0,0,0,0,0,...,1.0,119.0,100.0,30.0,2,30,3,1125,275,10
36,1.0,1,0,0,0,0,0,0,0,0,...,1.0,65.0,90.0,5.0,1,30,2,1125,353,38
38,2.0,1,0,0,0,0,0,0,0,0,...,1.0,87.0,100.0,25.0,1,0,2,1125,321,42
46,0.0,0,1,0,0,0,0,0,0,0,...,1.0,50.0,100.0,40.0,1,20,2,718,113,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20556,2.0,0,0,0,0,0,0,0,0,1,...,1.0,32.0,100.0,25.0,1,15,1,7,72,2
20559,1.0,0,0,0,0,0,0,0,0,1,...,2.0,140.0,500.0,15.0,1,10,1,1125,172,19
20563,0.0,0,0,0,0,0,0,0,0,1,...,1.0,22.0,146.0,10.0,1,0,19,19,52,0
20565,2.0,0,0,0,0,0,0,0,0,1,...,1.0,45.0,250.0,45.0,2,7,45,365,48,9
20566,2.0,0,0,0,0,0,0,0,0,1,...,3.0,200.0,500.0,50.0,4,25,7,14,0,1

# Check which columns are needed for our model and which are not

## Strength of Correlation

Variables with a higher absolute value of correlation with the dependent variable (closer to -1 or 1) typically have a stronger linear relationship. Variables with very low correlations (close to 0) might not be useful predictors on their own. However, even variables with lower correlations could be significant in the presence of other variables, especially if they capture different aspects of the dependent variable's variability.

In [727]:
correlation_matrix = final_df.corr()
price_correlation = correlation_matrix['Price']
price_correlation_sorted_desc = price_correlation.sort_values(ascending=False)
price_correlation_sorted_desc

Price                            1.000000
Accommodates                     0.646198
Bedrooms                         0.588695
Beds                             0.572940
Cleaning Fee                     0.513685
Guests Included                  0.465464
Bathrooms                        0.427488
Room Type_Entire home/apt        0.395279
Security Deposit                 0.236750
Extra People                     0.209016
Neighbourhood_Mitte              0.177352
Cancellation Policy              0.157340
Availability 365                 0.150585
Number of Reviews                0.070780
Neighbourhood_Prenzlauer Berg    0.067529
Neighbourhood_Wilmersdorf        0.014113
Neighbourhood_Kreuzberg          0.011142
Neighbourhood_Charlottenburg    -0.000477
Maximum Nights                  -0.000609
Neighbourhood_Tempelhof         -0.023132
Room Type_Shared room           -0.026992
Neighbourhood_SchÃ¶neberg        -0.028918
Neighbourhood_Friedrichshain    -0.040091
Neighbourhood_Moabit            -0.044111
Neighbourhood_Pankow            -0.045460
Minimum Nights                  -0.051756
Neighbourhood_NeukÃ¶lln          -0.089545
Neighbourhood_Wedding           -0.092240
Room Type_Private room          -0.393229
Name: Price, dtype: float64

## Statistical Significance

It's important to test the statistical significance of the correlation coefficients to ensure that the observed relationship is not due to random chance. This can be done using tests such as the Pearson correlation significance test.

In [728]:
from scipy.stats import pearsonr

# Assuming final_df is your DataFrame and it has been defined earlier

final_col = final_df.columns

for col in final_col:
    # Skip the 'Price' column to avoid calculating its correlation with itself
    if col == 'Price':
        continue

    # Calculate the Pearson correlation coefficient and p-value
    corr_coefficient, p_value = pearsonr(final_df[col], final_df['Price'])

    # Check if the p-value is less than or equal to 0.05
    if p_value > 0.05:
        # Print the column name, correlation coefficient, and p-value for significant correlations
        print(f'{col} Pearson Correlation Coefficient: {corr_coefficient:.3f}')
        print(f'{col} P-value: {p_value:.3e}')

Neighbourhood_Charlottenburg Pearson Correlation Coefficient: -0.000
Neighbourhood_Charlottenburg P-value: 9.760e-01
Neighbourhood_Kreuzberg Pearson Correlation Coefficient: 0.011
Neighbourhood_Kreuzberg P-value: 4.815e-01
Neighbourhood_SchÃ¶neberg Pearson Correlation Coefficient: -0.029
Neighbourhood_SchÃ¶neberg P-value: 6.768e-02
Neighbourhood_Tempelhof Pearson Correlation Coefficient: -0.023
Neighbourhood_Tempelhof P-value: 1.439e-01
Neighbourhood_Wilmersdorf Pearson Correlation Coefficient: 0.014
Neighbourhood_Wilmersdorf P-value: 3.726e-01
Room Type_Shared room Pearson Correlation Coefficient: -0.027
Room Type_Shared room P-value: 8.812e-02
Maximum Nights Pearson Correlation Coefficient: -0.001
Maximum Nights P-value: 9.693e-01

- Correlation Coefficient (corr_coefficient): This value ranges from -1 to 1, where closer to 1 or -1 indicates a strong linear relationship, and closer to 0 indicates a weak or no linear relationship.
- P-value (p_value): This value helps you determine the significance of the correlation. A common threshold for significance is 0.05:
If the p-value is less than or equal to 0.05, the correlation is considered statistically significant, meaning there's strong evidence that the true correlation is not zero.
If the p-value is greater than 0.05, the correlation is not considered statistically significant, suggesting that the observed correlation might be due to random variation in the sample.

Droped all Property Type on top

Drop Latitude, Longitude, Maximum Nights, Maximum Nights, Review Scores Rating, Review Scores Accuracy, Review Scores Location

In [729]:
final_df = final_df.drop(['Room Type_Shared room', 'Beds', 'Neighbourhood_Wilmersdorf'], axis=1)

In [730]:
final_df['Room Type_Private'] = (final_df['Room Type_Private room'] | final_df['Room Type_Entire home/apt']).astype(int)
final_df = final_df.drop(['Room Type_Private room', 'Room Type_Entire home/apt'], axis=1)

## Multicollinearity

Including variables that are highly correlated with each other (not just with the dependent variable) can lead to multicollinearity, which can skew the results of a linear regression model. It's often advisable to avoid including variables that have a very high correlation with one another.

In [731]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

# Assuming final_df is your DataFrame and it has been defined earlier, and contains only explanatory variables
X = add_constant(final_df)

# Calculate VIF for each explanatory variable
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

# Filter out features with VIF equal to or greater than 5
high_vif = vif_data[vif_data["VIF"] >= 5]

print(high_vif)

                         feature         VIF
0                          const  418.702620
3   Neighbourhood_Friedrichshain    5.001573
4        Neighbourhood_Kreuzberg    5.824870
5            Neighbourhood_Mitte    5.382128
7         Neighbourhood_NeukÃ¶lln    5.800317
9  Neighbourhood_Prenzlauer Berg    6.071329

- A rule of thumb is that if VIF is 1, then the variable is not correlated with any other variables.
- A VIF between 1 and 5 suggests moderate correlation, but it's often not severe enough to require attention.
- A VIF greater than 5 or 10 indicates high multicollinearity that you may want to address by removing the variable or using techniques like Principal Component Analysis (PCA) or partial least squares regression.


- Drop one Dummy column in categorical

## Practical Thresholds

As a rule of thumb, some analysts might consider variables with a correlation coefficient above a certain threshold, such as |0.2| or |0.3|, as potentially useful predictors. This threshold is arbitrary and should be adjusted based on the context of the analysis and the points mentioned above.

In [732]:
import numpy as np  # Ensure numpy is imported

# Calculate correlation matrix
corr_matrix = final_df.corr().abs()

# Select upper triangle of correlation matrix to avoid double counting
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool_))

# Define a correlation coefficient threshold
corr_threshold = 0.7

# Find features with correlation greater than the threshold
high_corr_pairs = [(var1, var2) for var1 in upper_tri.columns for var2 in upper_tri.index if upper_tri.at[var2, var1] > corr_threshold]

print("Highly correlated pairs:", high_corr_pairs)

Highly correlated pairs: []

- Review and Understand: Understand the role of these variables in your analysis. Are they essential? Can the information they provide be captured by other variables?
- Remove or Combine Variables: Consider removing one of the variables in a highly correlated pair or combining variables to reduce multicollinearity.
- Regularization: Apply regularization methods (Lasso or Ridge regression) that can handle multicollinearity by penalizing the size of coefficients.
- Dimensionality Reduction: Use techniques like Principal Component Analysis (PCA) to create a set of uncorrelated predictors.

In [733]:
final_df.columns

Index(['Cancellation Policy', 'Neighbourhood_Charlottenburg',
       'Neighbourhood_Friedrichshain', 'Neighbourhood_Kreuzberg',
       'Neighbourhood_Mitte', 'Neighbourhood_Moabit', 'Neighbourhood_NeukÃ¶lln',
       'Neighbourhood_Pankow', 'Neighbourhood_Prenzlauer Berg',
       'Neighbourhood_SchÃ¶neberg', 'Neighbourhood_Tempelhof',
       'Neighbourhood_Wedding', 'Accommodates', 'Bathrooms', 'Bedrooms',
       'Price', 'Security Deposit', 'Cleaning Fee', 'Guests Included',
       'Extra People', 'Minimum Nights', 'Maximum Nights', 'Availability 365',
       'Number of Reviews', 'Room Type_Private'],
      dtype='object')

Droped all Bed Types on top

In [734]:
final_df.to_csv("clean_airbnb_df_berlin.csv")