In [1]:
pip install xlrd

Requirement already satisfied: xlrd in /Users/miriamg/opt/anaconda3/lib/python3.8/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [27]:
#Importing our defined functions
from clean_data_functions import *

In [28]:
import pandas as pd
import numpy as np

url = '/Users/miriamg/Documents/Mid-Term-Project_ML_Ironhack/Mid-term project/Cleaning/listings.csv'
airbnb_df = pd.read_csv(url)

# Cleaning data_science Data Frame

In [29]:
airbnb_df = airbnb_df.drop(['source', 'listing_url', 'scrape_id', 'last_scraped', 'last_scraped', 'name', 'description', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'calendar_updated', 'calendar_last_scraped', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_accuracy' , 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms','minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'property_type', 'amenities', 'host_since'], axis=1)

In [30]:
airbnb_df = airbnb_df.dropna(axis=1, how='all')

In [31]:
airbnb_df.columns

Index(['id', 'host_is_superhost', 'neighbourhood_cleansed', 'room_type',
       'accommodates', 'bathrooms_text', 'beds', 'price', 'availability_365',
       'number_of_reviews', 'review_scores_rating'],
      dtype='object')

In [32]:
airbnb_df

,id,host_is_superhost,neighbourhood_cleansed,room_type,accommodates,bathrooms_text,beds,price,availability_365,number_of_reviews,review_scores_rating
0,35797,f,Cuajimalpa de Morelos,Entire home/apt,2,1 bath,1.0,"$3,390.00",363,0,NaN
1,44616,f,Cuauhtémoc,Entire home/apt,14,5.5 baths,8.0,"$18,000.00",365,64,4.58
2,1441434,t,Cuauhtémoc,Entire home/apt,2,1.5 baths,1.0,"$3,350.00",89,221,4.90
3,607833,f,Gustavo A. Madero,Private room,2,1 bath,1.0,$339.00,86,6,4.83
4,609012,f,Cuauhtémoc,Entire home/apt,2,1.5 baths,2.0,"$1,273.00",329,22,4.67
...,...,...,...,...,...,...,...,...,...,...,...
26755,1052851736384847931,f,Benito Juárez,Entire home/apt,2,1 bath,1.0,$970.00,265,0,NaN
26756,1052862129515501207,f,Cuauhtémoc,Private room,2,1 bath,1.0,$175.00,262,0,NaN
26757,1052874102314225353,f,Cuauhtémoc,Entire home/apt,5,2 baths,3.0,"$1,166.00",266,0,NaN
26758,1052898145299209233,f,Cuauhtémoc,Private room,2,1 bath,1.0,$286.00,267,0,NaN
26759,1052927676643283947,f,Benito Juárez,Entire home/apt,2,1 bath,NaN,$800.00,269,0,NaN

In [33]:
#Getting initial overview of data frame
data_frame_overview(airbnb_df)

Column names:
 Index(['id', 'host_is_superhost', 'neighbourhood_cleansed', 'room_type',
       'accommodates', 'bathrooms_text', 'beds', 'price', 'availability_365',
       'number_of_reviews', 'review_scores_rating'],
      dtype='object')

Dimensions: (26760, 11)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26760 entries, 0 to 26759
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      26760 non-null  int64
 1   host_is_superhost       26522 non-null  object
 2   neighbourhood_cleansed  26760 non-null  object
 3   room_type               26760 non-null  object
 4   accommodates            26760 non-null  int64
 5   bathrooms_text          26739 non-null  object
 6   beds                    26366 non-null  float64
 7   price                   25729 non-null  object
 8   availability_365        26760 non-null  int64
 9   number_of_reviews       26760 non-null  int64
 10  review_scores_rating    22967 non-null  float64
dtypes: float64(2), int64(4), object(5)
memory usage: 2.2+ MB
None

,id,host_is_superhost,neighbourhood_cleansed,room_type,accommodates,bathrooms_text,beds,price,availability_365,number_of_reviews,review_scores_rating
0,35797,f,Cuajimalpa de Morelos,Entire home/apt,2,1 bath,1.0,"$3,390.00",363,0,NaN
1,44616,f,Cuauhtémoc,Entire home/apt,14,5.5 baths,8.0,"$18,000.00",365,64,4.58
2,1441434,t,Cuauhtémoc,Entire home/apt,2,1.5 baths,1.0,"$3,350.00",89,221,4.90
3,607833,f,Gustavo A. Madero,Private room,2,1 bath,1.0,$339.00,86,6,4.83
4,609012,f,Cuauhtémoc,Entire home/apt,2,1.5 baths,2.0,"$1,273.00",329,22,4.67
5,1462549,t,Miguel Hidalgo,Entire home/apt,2,2 baths,2.0,"$1,002.00",115,99,4.90
6,61792,t,Cuauhtémoc,Private room,2,1 private bath,1.0,"$1,018.00",180,64,4.92
7,1476127,t,Benito Juárez,Private room,2,1 private bath,1.0,$950.00,345,237,4.97
8,67703,f,Cuauhtémoc,Entire home/apt,4,1 bath,2.0,"$1,794.00",329,46,4.89
9,1483498,t,Cuauhtémoc,Entire home/apt,4,1.5 baths,2.0,"$1,002.00",67,244,4.79

In [34]:
airbnb_df = airbnb_df.dropna(subset=['price'])

In [35]:
null_check(airbnb_df)

Total null values per row:
0        1
1        0
2        0
3        0
4        0
        ..
26755    1
26756    1
26757    1
26758    1
26759    2
Length: 25729, dtype: int64

Total null values per column:
id                           0
host_is_superhost          235
neighbourhood_cleansed       0
room_type                    0
accommodates                 0
bathrooms_text              19
beds                       378
price                        0
availability_365             0
number_of_reviews            0
review_scores_rating      3456
dtype: int64

In [36]:
airbnb_df

,id,host_is_superhost,neighbourhood_cleansed,room_type,accommodates,bathrooms_text,beds,price,availability_365,number_of_reviews,review_scores_rating
0,35797,f,Cuajimalpa de Morelos,Entire home/apt,2,1 bath,1.0,"$3,390.00",363,0,NaN
1,44616,f,Cuauhtémoc,Entire home/apt,14,5.5 baths,8.0,"$18,000.00",365,64,4.58
2,1441434,t,Cuauhtémoc,Entire home/apt,2,1.5 baths,1.0,"$3,350.00",89,221,4.90
3,607833,f,Gustavo A. Madero,Private room,2,1 bath,1.0,$339.00,86,6,4.83
4,609012,f,Cuauhtémoc,Entire home/apt,2,1.5 baths,2.0,"$1,273.00",329,22,4.67
...,...,...,...,...,...,...,...,...,...,...,...
26755,1052851736384847931,f,Benito Juárez,Entire home/apt,2,1 bath,1.0,$970.00,265,0,NaN
26756,1052862129515501207,f,Cuauhtémoc,Private room,2,1 bath,1.0,$175.00,262,0,NaN
26757,1052874102314225353,f,Cuauhtémoc,Entire home/apt,5,2 baths,3.0,"$1,166.00",266,0,NaN
26758,1052898145299209233,f,Cuauhtémoc,Private room,2,1 bath,1.0,$286.00,267,0,NaN
26759,1052927676643283947,f,Benito Juárez,Entire home/apt,2,1 bath,NaN,$800.00,269,0,NaN

In [38]:
airbnb_df['beds'] = np.where(pd.isnull(airbnb_df['beds']), np.floor(airbnb_df['accommodates'] / 2), airbnb_df['beds']).astype(int)
airbnb_df['host_is_superhost'] = airbnb_df['host_is_superhost'].fillna('f')
airbnb_df = airbnb_df.dropna(subset=['bathrooms_text'])
airbnb_df['review_scores_rating'] = airbnb_df['review_scores_rating'].fillna(0)
airbnb_df['bathrooms_text'] = airbnb_df['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)
airbnb_df['bathrooms_text'] = airbnb_df['bathrooms_text'].fillna(1)

<ipython-input-38-cec5fe0c267b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb_df['beds'] = np.where(pd.isnull(airbnb_df['beds']), np.floor(airbnb_df['accommodates'] / 2), airbnb_df['beds']).astype(int)
<ipython-input-38-cec5fe0c267b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb_df['host_is_superhost'] = airbnb_df['host_is_superhost'].fillna('f')

AttributeError: Can only use .str accessor with string values!

In [26]:
null_check(airbnb_df)

Total null values per row:
0        0
1        0
2        0
3        0
4        0
        ..
26755    0
26756    0
26757    0
26758    0
26759    0
Length: 25710, dtype: int64

Total null values per column:
id                      0
superhost               0
neighbourhood           0
room_type               0
accommodates            0
bathrooms               0
beds                    0
price                   0
availability_365        0
number_of_reviews       0
review_scores_rating    0
dtype: int64

In [29]:
dup_check(airbnb_df)

Duplicates found: False

Number of duplicates: 0

In [20]:
#Applying the reformatting the names of the columns
column_name_mapping = {'host_is_superhost' : 'superhost', 'neighbourhood_cleansed' : 'neighbourhood', 'bathrooms_text' : 'bathrooms'}

format_column_names(airbnb_df, column_name_mapping)

New column names:
 Index(['id', 'superhost', 'neighbourhood', 'room_type', 'accommodates',
       'bathrooms', 'beds', 'price', 'availability_365', 'number_of_reviews',
       'review_scores_rating'],
      dtype='object')

/Users/miriamg/Documents/Mid-Term-Project_ML_Ironhack/Mid-term project/Cleaning/clean_data_functions.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame.rename(columns={old_name: new_name}, inplace=True)

In [21]:
airbnb_df

,id,superhost,neighbourhood,room_type,accommodates,bathrooms,beds,price,availability_365,number_of_reviews,review_scores_rating
0,35797,f,Cuajimalpa de Morelos,Entire home/apt,2,1.0,1,"$3,390.00",363,0,0.00
1,44616,f,Cuauhtémoc,Entire home/apt,14,5.5,8,"$18,000.00",365,64,4.58
2,1441434,t,Cuauhtémoc,Entire home/apt,2,1.5,1,"$3,350.00",89,221,4.90
3,607833,f,Gustavo A. Madero,Private room,2,1.0,1,$339.00,86,6,4.83
4,609012,f,Cuauhtémoc,Entire home/apt,2,1.5,2,"$1,273.00",329,22,4.67
...,...,...,...,...,...,...,...,...,...,...,...
26755,1052851736384847931,f,Benito Juárez,Entire home/apt,2,1.0,1,$970.00,265,0,0.00
26756,1052862129515501207,f,Cuauhtémoc,Private room,2,1.0,1,$175.00,262,0,0.00
26757,1052874102314225353,f,Cuauhtémoc,Entire home/apt,5,2.0,3,"$1,166.00",266,0,0.00
26758,1052898145299209233,f,Cuauhtémoc,Private room,2,1.0,1,$286.00,267,0,0.00
26759,1052927676643283947,f,Benito Juárez,Entire home/apt,2,1.0,1,$800.00,269,0,0.00